# arxivの学問領域の指定
subject: 'cat:quant-ph'

# 検索キーワード
keywords:
    error: 1
    noise: 1
    qubit: 1
    computer: 1
    computation: 1
    silicon: 1
    NISQ: 1
    algorithm: 1

# 通知の閾値
score_threshold: 1
